### ISSUE TITLE
Analyze and visualize meta data

### ISSUE THREAD

**Issue by ahmedtarek26** [DevMed22/Revive_My_Memory#34]
The ADNI data contains metadata that describes features about the patient, MRI type, image processing protocols, and more

**Comment by ahmedtarek26** [comment]
@Omarelsherif010 
Have you used XML data with python before?

**Comment by Omarelsherif010** [comment]
I think I have used it one time in the past(Can't remember to be honest😂)
But we can handle it together as we are not going to do so much in the analysis of the metadata. So maybe this tutorial is a good first step (https://www.datacamp.com/tutorial/python-xml-elementtree)

**Comment by ahmedtarek26** [comment]
Cool,
I think it's a little similar to working with JSON files
