### ISSUE TITLE
Download ADNI DCM images with the meta data

### ISSUE THREAD

**Issue by Omarelsherif010** [DevMed22/Revive_My_Memory#35]
We need to download dicom images as zip files and upload it to Google Drive in order to run our model on Colab because of the size of the data

**Comment by Omarelsherif010** [comment]
@ahmedtarek26 
I have already downloaded the meta data (csv files)
If you can do the big part(MRI images), then upload to our shared drive

**Comment by ahmedtarek26** [comment]
@ahmedtarek26 
Nice, I have uploaded EMCI MRI data and I'll try it on collab then i'll upload the rest of the data

**Comment by Omarelsherif010** [comment]
Great 
I have time today so let's meet 3 pm to finish this together

**Comment by ahmedtarek26** [comment]
Okay

**Comment by ahmedtarek26** [comment]
We downloaded sample data
I'll reopen it when we download it at a cloud service
