### ISSUE TITLE
Provide summery of MLOps tools

### ISSUE THREAD

**Issue by Omarelsherif010** [DevMed22/Revive_My_Memory#43]
Your assistant in this task is @Omarelsherif010 

We need to know common MLOps tools available inside the developer student pack and free tools. We need to know the role of every tool and where it is in the circle

**Comment by ahmedtarek26** [comment]
From this [video ](https://youtu.be/f8AtpzmRzFc)i find a summary of MLOps tools (
Important tools:

1. GitHub Actions
2. Docker

**Comment by ahmedtarek26** [comment]
There are two ways for creating MLOps products:

**1. Using open-source MLOps software for each step**


- Experiment Tracking and Model Metadata Management Tools
These tools allow you to manage model metadata and help with experiment tracking
    1. MLFlow
    2. Comet ML
    3. Weights & Biases

-  Orchestration and Workflow Pipelines MLOps Tools
help you create data science projects and manage machine learning workflows
    1. Prefect
    2. MLflow
    3. Metaflow
    4. Kedro
- Data and Pipeline Versioning Tools
With these MLOps tools, you can manage tasks around data and pipeline versioning
    1. Pachyderm
    2. Data Version Control (DVC)
- Model Deployment and Serving Tools
    1. TFX
    2. BentoML
    3. Cortex
- Model Monitoring in Production ML Ops Tools
Whether your ML model is in development, validation, or deployed to production, these tools can help you monitor a range of factors
    1. Evidently
    2. Fiddler
    3. Censius AI

**2. Using End-to-End MLOps Platforms**
- Azure ML services, Azure Pipelines
- AWS SageMaker
- DagsHub
- Kubeflow



**Resources:**

[Example of End-to-End MLOps project](https://www.datacamp.com/tutorial/tutorial-machine-learning-pipelines-mlops-deployment)

 @amr-atif @anasos20 Have a look on this link and this image

![image](https://user-images.githubusercontent.com/77227944/221666187-16026837-040f-45c8-b240-534eefb568f9.png)


1. https://www.datacamp.com/blog/top-mlops-tools
2. https://neptune.ai/blog/mlops
3. https://research.aimultiple.com/mlops/
4. https://www.youtube.com/watch?v=nVjNBKLCMKE&list=PLZk8J6FocZbYeCQ0c8vM_po_Sbg5R9dZe&index=2&ab_channel=SaschaDittmann

**Comment by amr-atif** [comment]
that looks good Ahmed very useful @ahmedtarek26

**Comment by anasos20** [comment]
@ahmedtarek26  Provide a word file and push it to the Doc folder in our repo
Great Work BTW keep going ❤️

**Comment by ahmedtarek26** [comment]
@anasos20 I'll do it now
