### ISSUE TITLE
Run pre-build model on Azure ML studio

### ISSUE THREAD

**Issue by Omarelsherif010** [DevMed22/Revive_My_Memory#50]
Your assistant in this task is @Omarelsherif010 

Use any prebuild model on Azure ML Studio. We need to see the speed and difference between colab

**Comment by ahmedtarek26** [comment]
Before running our pre-build model we need to understand the Azure ML studio,After searched on this topic and found this useful [video](https://youtu.be/rM9gNrYulM0)

I'll follow the video content and tell you the updates

**Comment by Omarelsherif010** [comment]
OK
After you finish, let me know to activate the ambassador azure account❤️

**Comment by Omarelsherif010** [comment]
We are good with what we have built inside Azure ML studio, so I will close this one
