### ISSUE TITLE
Provide steps on transferring big data between providers

### ISSUE THREAD

**Issue by Omarelsherif010** [DevMed22/Revive_My_Memory#52]
Your assistant in this task is @ahmedtarek26 

Ask AI experts how they deal with big data in their analysis regarding storage and moving between providers.
Search for available solutions on YouTube

**Comment by ahmedtarek26** [comment]
I have some knowledge about this issue.
EX: to use data from a big data that is stored in a server you 'll need the API of this data and use it in your cloud service

**Comment by Omarelsherif010** [comment]
Good news
So we can try to do it together, let me know if are available on Monday

**Comment by Omarelsherif010** [comment]
We are going to use VM on Azure to download ADNI data and upload to OneDrive then access the data from Azure Machine Learning Studio or Azure DevOps
