### ISSUE TITLE
Build VM on Azure

### ISSUE THREAD

**Issue by Omarelsherif010** [DevMed22/Revive_My_Memory#55]
Your assistant in this task is @anasos20 

We need to build a VM on Azure and try to use it to download ADNI data

**Comment by Omarelsherif010** [comment]
I have already built the VM on Azure with the help of @anasos20 and downloaded a sample of our data to the VM on Azure then uploaded it to OneDrive.

@ahmedtarek26 
We will need to try training a model on Azure using this sample from OneDrive

**Comment by ahmedtarek26** [comment]
Great Job @Omarelsherif010 
We need to make sure that we can access and preview the data in Azure like our first try this morning.
We'll try again and solve this problem then download the rest of the data 

Now, I think that this issue is already done
