### ISSUE TITLE
Read and understand MCI and AD paper and discuss it with our supervisor

### ISSUE THREAD

**Issue by Omarelsherif010** [DevMed22/Revive_My_Memory#6]

**Comment by ahmedtarek26** [comment]
The research groups in ADNI data are

1. **CN**: cognitively normal
2. **EMCI**: early mild cognitive impairment
3. **LMCI**: late mild cognitive impairment
4. **AD**: Alzheimer's disease.
5. **SMC**: Significant Memory Concern.

**Comment by Omarelsherif010** [comment]
Great, 
I think we can close this issue for now and reopen it in the second sprint (when building MultiModel Clustering ), what do you think?

**Comment by ahmedtarek26** [comment]
I agree,
In the next sprint we can reopen it and add more details about each research group
